Controllers/Form_MasterController.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Data;
using VendorPurchaseProject.DBHandler;
using VendorPurchaseProject.Models;
using VendorPurchaseProject.Models.ModelDTO;

namespace VendorPurchaseProject.Controllers
{
    public class Form_MasterController : Controller
    {
        private readonly IDBService _dbService;

        public Form_MasterController(IDBService dbService)
        {
            _dbService = dbService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult VendorMaster()
        {
            return View();
        }
        public IActionResult PurchaseMaster()
        {
            return View();
        }
        public IActionResult MaterialMaster()
        {
            return View();
        }
        [HttpPost]
        public async Task<List<VendorModel>> GetVendorDataByVendorCode([FromBody] VendorModel vendorDetail)
        {
            var parameters = new DynamicParameters();
            parameters.Add("@Vendor_Id", vendorDetail.Vendor_Id);
            var vendorData = await _dbService.GetAll<VendorModel>("sp_get_vp_Vendor__Master_Detail_ByCode", parameters);
            return vendorData;
        }
        [HttpPost]
        public async Task<JsonResult> SaveVendorDetail([FromBody] VendorDTO vendorDetail)
        {
            if (ModelState.IsValid)
            {
                var parameters = new DynamicParameters();
                parameters.Add("@Name", vendorDetail.Name);
                parameters.Add("@Email", vendorDetail.Email);
                parameters.Add("@AddressLine1", vendorDetail.AddressLine1);
                parameters.Add("@ValidTill", vendorDetail.ValidTill);
                parameters.Add("@Contact", vendorDetail.Contact);
                parameters.Add("@AddressLine2", vendorDetail.AddressLine2);
                parameters.Add("@isChecked", vendorDetail.isChecked);
                parameters.Add("@NewId", dbType: DbType.Int32, direction: ParameterDirection.Output);
                await _dbService.EditData("sp_ins_vp_Vendor_Master", parameters);
                var res = parameters.Get<int>("@NewId");
                var result = new { success = true, message = res };
                return Json(result);
            }
            else
            {
                var result = new { success = false, message = "Invalid data." };
                return Json(result);
            }
        }
        [HttpPost]
        public async Task<JsonResult> DeleteVendorDetail([FromBody] VendorModel vendorDetail)
        {
            try
            {
                var parameters = new DynamicParameters();
                parameters.Add("@Vendor_Id", vendorDetail.Vendor_Id);
                parameters.Add("@NewId", dbType: DbType.Int32, direction: ParameterDirection.Output);
                await _dbService.EditData("sp_del_vp_Vendor_Master", parameters);
                var res = parameters.Get<int>("@NewId");
                var result = new { success = true, message = res };
                return Json(result);
            }
            catch (Exception ex)
            {
                var result = new { success = false, message = ex.Message };
                return Json(result);
            }
        }
        [HttpPost]
        public async Task<JsonResult> UpdateVendorDetail([FromBody] VendorModel vendorDetail)
        {
            try
            {
                var parameters = new DynamicParameters();
                parameters.Add("@Vendor_Id", vendorDetail.Vendor_Id);
                parameters.Add("@Name", vendorDetail.Name);
                parameters.Add("@Email", vendorDetail.Email);
                parameters.Add("@AddressLine1", vendorDetail.AddressLine1);
                parameters.Add("@ValidTill", vendorDetail.ValidTill);
                parameters.Add("@Contact", vendorDetail.Contact);
                parameters.Add("@AddressLine2", vendorDetail.AddressLine2);
                parameters.Add("@isChecked", vendorDetail.isChecked);
                parameters.Add("@NewId", dbType: DbType.Int32, direction: ParameterDirection.Output);
                await _dbService.EditData("sp_upd_vp_Vendor_Master", parameters);
                var res = parameters.Get<int>("@NewId");
                var result = new { success = true, message = res };
                return Json(result);
            }
            catch (Exception ex)
            {
                var result = new { success = false, message = ex.Message };
                return Json(result);
            }
        }
        [HttpPost]
        public async Task<List<MaterialModel>> GetMaterialDataByVendorCode([FromBody] MaterialModel materialDetail)
        {
            var parameters = new DynamicParameters();
            parameters.Add("@Material_Id", materialDetail.Material_Id);
            var vendorData = await _dbService.GetAll<MaterialModel>("sp_get_vp_Material__Master_Detail_ByCode", parameters);
            return vendorData;
        }
        [HttpPost]
        public async Task<JsonResult> SaveMaterialDetail([FromBody] MaterialDTO materialDetail)
        {
            try
            {
                var parameters = new DynamicParameters();
                parameters.Add("@ShortTxt", materialDetail.ShortTxt);
                parameters.Add("@LongTxt", materialDetail.LongTxt);
                parameters.Add("@ReorderLevel", materialDetail.ReOrderLevel);
                parameters.Add("@MinOrderQuantity", materialDetail.MinOrderQuantity);
                parameters.Add("@Unit", materialDetail.Unit);
                parameters.Add("@isActive", materialDetail.isActive);
                parameters.Add("@NewId", dbType: DbType.Int32, direction: ParameterDirection.Output);
                await _dbService.EditData("sp_ins_vp_Material_Master", parameters);
                var res = parameters.Get<int>("@NewId");
                var result = new { success = true, message = res };
                return Json(result);
            }
            catch (Exception ex)
            {
                var result = new { success = false, message = ex.Message };
                return Json(result);
            }
        }
        [HttpPost]
        public async Task<JsonResult> DeleteMaterialDetail([FromBody] MaterialModel materialDetail)
        {
            try
            {
                var parameters = new DynamicParameters();
                parameters.Add("@Material_Id", materialDetail.Material_Id);
                parameters.Add("@NewId", dbType: DbType.Int32, direction: ParameterDirection.Output);
                await _dbService.EditData("sp_del_vp_Material_Master", parameters);
                var res = parameters.Get<int>("@NewId");
                var result = new { success = true, message = res };
                return Json(result);
            }
            catch (Exception ex)
            {
                var result = new { success = false, message = ex.Message };
                return Json(result);
            }
        }
        [HttpPost]
        public async Task<JsonResult> UpdateMaterialDetail([FromBody] MaterialModel materialDetail)
        {
            try
            {
                var parameters = new DynamicParameters();
                parameters.Add("@Material_Id", materialDetail.Material_Id);
                parameters.Add("@ShortTxt", materialDetail.ShortTxt);
                parameters.Add("@LongTxt", materialDetail.LongTxt);
                parameters.Add("@ReorderLevel", materialDetail.ReOrderLevel);
                parameters.Add("@MinOrderQuantity", materialDetail.MinOrderQuantity);
                parameters.Add("@Unit", materialDetail.Unit);
                parameters.Add("@isActive", materialDetail.isActive);
                parameters.Add("@NewId", dbType: DbType.Int32, direction: ParameterDirection.Output);
                await _dbService.EditData("sp_upd_vp_Material_Master", parameters);
                var res = parameters.Get<int>("@NewId");
                var result = new { success = true, message = res };
                return Json(result);
            }
            catch (Exception ex)
            {
                var result = new { success = false, message = ex.Message };
                return Json(result);
            }
        }
        [HttpPost]
        public async Task<List<PurchaseModel>> GetPurchaseDataByVendorCode([FromBody] PurchaseModel vendorDetail)
        {
            var parameters = new DynamicParameters();
            parameters.Add("@OrderNo", vendorDetail.OrderNo);
            var vendorData = await _dbService.GetAll<PurchaseModel>("sp_get_vp_Purchase_Master_Detail_ByCode", parameters);
            return vendorData;
        }
        [HttpPost]
        public async Task<JsonResult> SavePurchaseDetail([FromBody] PurchaseDTO purchaseDetail)
        {
            try
            {
                var parameters = new DynamicParameters();
                foreach (var purchaseDetails in purchaseDetail.PurchaseItems)
                {
                    parameters.Add("@ShortTxt", purchaseDetail.ShortTxt);
                    parameters.Add("@OrderDate", purchaseDetail.OrderDate);
                    parameters.Add("@OrderValue", purchaseDetail.OrderValue);
                    parameters.Add("@Quantity", purchaseDetails.Quantity);
                    parameters.Add("@Amount", purchaseDetails.Amount);
                    parameters.Add("@Rate", purchaseDetails.Rate);
                    parameters.Add("@Name", purchaseDetail.Vendor);
                    parameters.Add("@ValidTill", purchaseDetails.Expected_Date);
                    parameters.Add("@Notes", purchaseDetail.Notes);
                    parameters.Add("@Unit", purchaseDetail.Unit);
                    parameters.Add("@MCode", purchaseDetails.MCode);

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Diagnostics;
using VendorPurchaseProject.DBHandler;
using VendorPurchaseProject.Models;

namespace VendorPurchaseProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IDBService _dbService;

        public HomeController(ILogger<HomeController> logger, IDBService dbService)
        {
            _logger = logger;
            _dbService = dbService;
        }
       

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult VendorDetailList()
        {
            return View();
        }
        public IActionResult MaterialEntryList()
        {
            return View();
        }
        public IActionResult POEntryList()
        {
            return View();
        }
        public async Task<List<VendorModel>> GetVendorData()
        {
            try
            {
                var vendorData = await _dbService.GetAll<VendorModel>("sp_get_vp_Vendor_Master", new { });
                return vendorData;
            }
            catch (Exception ex)
            {
                return new List<VendorModel> {};
            }
           
        }
        public async Task<List<MaterialModel>> GetMaterialData()
        {
            var materialData = await _dbService.GetAll<MaterialModel>("sp_get_vp_Material_Master", new { });
            return materialData;
        }
        public async Task<List<PurchaseModel>> GetPurchaseData()
        {
            var purchaseData = await _dbService.GetAll<PurchaseModel>("sp_get_vp_Purchase_Master", new { });
            return purchaseData;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 ">Welcome To The Vendor Purchase Inventory</h1>
    <h5 class="mt-3">Have a Look Around And Explore the Application.</h5>
</div>

Views/Home/MaterialEntryList.cshtml
@{
    ViewData["Title"] = "PurchaseEntryList";
}

<div class="container mt-5">
    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white">
    <h3 class="mb-3">Material List</h3>
    <div class="d-flex justify-content-end mb-3">
        <button class="btn btn-secondary" onclick="location.href='@Url.Action("MaterialMaster", "Form_Master")'">Create</button>
        </div>
    </div>
    <table class="table table-bordered">
        <thead class="table-light">
            <tr>
                <th>Code</th>
                <th>Short Text</th>
                <th>Long Text</th>
                <th>Reorder Level</th>
                <th>Min Order Quantity</th>
                <th>Unit</th>
                <th>Is Active</th>
                <th colspan="2" class="text-center">Actions</th>
            </tr>
        </thead>
            <tbody id="materialTableBody">
           
        </tbody>
    </table>
</div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        loadMaterialData();
    });
    function loadMaterialData() {
        $.ajax({
            url: '/Home/GetMaterialData', // Your controller action URL
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                console.log("Venodr Data", data)
                var vendorHtml = '';
                data.forEach(function (material) {
                    vendorHtml += `
                <tr>
                        <td>${material.code}</td>
                            <td>${material.shortTxt}</td>
                            <td>${material.longTxt}</td>
                        <td>${material.reOrderLevel}</td>
                        <td>${material.minOrderQuantity}</td>
                            <td>${material.unit}</td>
                        <td>${material.isActive ? 'Yes' : 'No'}</td>
                    <td>
                                <button class="btn btn-sm btn-success" onclick="editMaterial(${material.material_Id})">Edit</button>
                    </td>
                    <td>
                                        <button class="btn btn-sm btn-danger" onclick="deleteMaterial(${material.material_Id},${material.isActive})">Delete</button>
                    </td>
                </tr>
            `;
                });
                $('#materialTableBody').html(vendorHtml);

            },
            error: function (xhr, status, error) {
                console.error('Error loading vendor data:', error);
                $('#vendorData').html('<p>Error loading vendor data.</p>');
            }
        });
        
    }
    function editMaterial(code) {
        window.location.href = '@Url.Action("MaterialMaster","Form_Master")' + '?Code=' + encodeURIComponent(code);;
    }
    function deleteMaterial(code, isActive) {
        if (isActive == false) {
            $.ajax({
                url: '/Form_Master/DeleteMaterialDetail',
                data: JSON.stringify({ Material_Id: code }),
                type: 'POST',
                contentType: "application/json",
                dataType: "json",
                success: function (response) {
                    if (response.success) {
                        alert("Vendor has been deleted successfully");
                        loadMaterialData();
                    } else {
                        alert({ message: "An error occurred" })
                    }
                },
                error: function (xhr, status, error) {
                    console.error("Error:", error);
                    errorCallback({ message: "An error occurred" });
                }
            });
        } else {
            alert(" Material is active, so It cannot be deleted");
        }
    }
</script>

Views/Home/POEntryList.cshtml
@{
    ViewData["Title"] = "POEntryList";
}
<div class="container mt-5">
    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white">
    <h3 class="mb-3">Purchase List</h3>

    <div class="d-flex justify-content-end mb-3">
        <button class="btn btn-secondary" onclick="location.href='@Url.Action("PurchaseMaster", "Form_Master")'">Create</button>
        </div>
    </div>
    <table class="table table-bordered">
        <thead class="table-light">
            <tr>
                <th colspan="1">PCode</th>
                <th colspan="1">MCode</th>
                <th colspan="1">Short Text</th>
                <th colspan="1">Vendor</th>
                <th colspan="1">Quantity</th>
                <th colspan="1">Rate</th>
                <th colspan="1">Amount</th>
                <th colspan="1">OrderValue</th>
                <th colspan="1">OrderDate</th>
                <th colspan="1">Unit</th>
                <th colspan="1">Exp Date</th>
                <th colspan="2" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody id="purchaseTableBody">
        </tbody>
    </table>
</div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        loadPurchaseData();
    });
    function loadPurchaseData() {
        $.ajax({
            url: '/Home/GetPurchaseData', // Your controller action URL
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                console.log("Venodr Data", data)
                var vendorHtml = '';
                data.forEach(function (purchase) {
                    vendorHtml += `
                    <tr>
                                <td>${purchase.pCode}</td>
                                    <td>${purchase.mCode}</td>
                                    <td>${purchase.shortTxt}</td>
                                        <td>${purchase.vendor}</td>
                                              <td>${purchase.quantity}</td>
                                               <td>${purchase.rate}</td>
                                                    <td>${purchase.amount}</td>
                                        <td>${purchase.orderValue}</td>
                                    <td>${purchase.orderDate}</td>
                                    <td>${purchase.unit}</td>
                                    <td>${purchase.expected_Date}</td>
                        <td>
                                            <button class="btn btn-sm btn-success" onclick="editPurchase(${purchase.orderNo})">Edit</button>
                        </td>
                        <td>
                                                        <button class="btn btn-sm btn-danger" onclick="deletePurchase(${purchase.orderNo})">Delete</button>
                        </td>
                    </tr>
                `;
                });
                $('#purchaseTableBody').html(vendorHtml);

            },
            error: function (xhr, status, error) {
                console.error('Error loading vendor data:', error);
                $('#vendorData').html('<p>Error loading vendor data.</p>');
            }
        });

    }
    function editPurchase(code) {
        window.location.href = '@Url.Action("PurchaseMaster","Form_Master")' + '?Code=' + encodeURIComponent(code);;
    }
    function deletePurchase(code, isActive) {
            $.ajax({
                url: '/Form_Master/DeletePurchaseDetail',
                data: JSON.stringify({ OrderNo: code }),
                type: 'POST',
                contentType: "application/json",
                dataType: "json",
                success: function (response) {
                    if (response.success) {
                        alert("Vendor has been deleted successfully");
                    loadPurchaseData();
                    } else {
                        alert({ message: "An error occurred" })
                    }
                },
                error: function (xhr, status, error) {
                    console.error("Error:", error);
                    errorCallback({ message: "An error occurred" });
                }
            });
    }
</script>

Views/Home/VendorDetailList.cshtml
    <title>Vendor List</title>
    <div>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="~/js/script/baseservice.js"></script>
   </div>
    <div class="container mt-5">
    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white">
        <h3 class="mb-3">Vendor List</h3>
        <div class="d-flex justify-content-end mb-3">
        <button class="btn btn-secondary" onclick="location.href='@Url.Action("VendorMaster", "Form_Master")'">Create</button>
        </div>
        </div>
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Contact Email</th>
                    <th>Contact Number</th>
                    <th>Valid Till Date</th>
                    <th>Is Active</th>
                    <th colspan="2" class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody id="vendorTableBody">
                <!-- Rows will be added dynamically here -->
            </tbody>
        </table>
    </div>
    </div>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
            // Example: Load data on page load
            loadVendorData();
       //BaseService('Home', 'GetVendorData', null, 'GET',
       //     function (response) {
       //         if (response) {
       //             console.log("Vendor Data:", response);
       //         }
       //     },
       //     function (error) {
       //         console.error("Error fetching vendor data:", error.message);
       //     }
       // );

        });
        function loadVendorData() {
        
            $.ajax({
            url: '/Home/GetVendorData', // Your controller action URL
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    console.log("Venodr Data", data)
                var vendorHtml = '';
                data.forEach(function (vendor) {
                    vendorHtml += `
            <tr>
                <td>${vendor.code}</td>
                <td>${vendor.name}</td>
                <td>${vendor.email}</td>
                <td>${vendor.contact}</td>
                <td>${vendor.validTill}</td>
                <td>${vendor.isChecked ? 'Yes' : 'No'}</td>
                <td>
                    <button class="btn btn-sm btn-success" onclick="editVendor(${vendor.vendor_Id})">Edit</button>
                </td>
                <td>
                            <button class="btn btn-sm btn-danger" onclick="deleteVendor(${vendor.vendor_Id},${vendor.isChecked})">Delete</button>
                </td>
            </tr>
        `;
                });
                $('#vendorTableBody').html(vendorHtml);

                },
                error: function (xhr, status, error) {
                    console.error('Error loading vendor data:', error);
                    $('#vendorData').html('<p>Error loading vendor data.</p>');
                }
            });
            
    }
    function editVendor(code){
        window.location.href = '@Url.Action("VendorMaster","Form_Master")' + '?vendorCode=' + encodeURIComponent(code);;
    }

    function deleteVendor(code,isChecked){
        if (isChecked == false) {
            $.ajax({
                url: '/Form_Master/DeleteVendorDetail',
                data: JSON.stringify({Vendor_Id:code}),
                type: 'POST', 
                contentType: "application/json", 
                dataType: "json",
                success: function (response) {
                    if (response.success) {
                        alert("Vendor has been deleted successfully");
                        loadVendorData();
                    } else {
                        alert({ message: "An error occurred" })
                    }
                },
                error: function (xhr, status, error) {
                    console.error("Error:", error);
                    errorCallback({ message: "An error occurred" });
                }
            });
        }else{
            alert(" Vendor is active, So It cannot be deleted");
        }
    }
</script>